language: node_js
node_js:
  - "6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
env:
  - CXX=g++-4.8

cache:
  yarn: true
  directories:
    - node_modules

after_success:
  - bash <(curl -s https://codecov.io/bash)
