version: '2'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    ports:
      - "80:80"
    depends_on:
      - server

  database:
    image: rethinkdb:2

  server:
    build: .
    depends_on:
      - database

