// flow-typed signature: eb47752969a75ea8d829d67adbf481d5
// flow-typed version: <<STUB>>/just-wait_v^1.0.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'just-wait'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'just-wait' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'just-wait/bin/just-wait' {
  declare module.exports: any;
}

// Filename aliases
declare module 'just-wait/bin/just-wait.js' {
  declare module.exports: $Exports<'just-wait/bin/just-wait'>;
}
declare module 'just-wait/index' {
  declare module.exports: $Exports<'just-wait'>;
}
declare module 'just-wait/index.js' {
  declare module.exports: $Exports<'just-wait'>;
}
