// flow-typed signature: 9e25dfd6eac2b9c7e3520c1b9ad958fd
// flow-typed version: <<STUB>>/react-onclickoutside_v^5.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-onclickoutside'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-onclickoutside' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-onclickoutside/index' {
  declare module.exports: $Exports<'react-onclickoutside'>;
}
declare module 'react-onclickoutside/index.js' {
  declare module.exports: $Exports<'react-onclickoutside'>;
}
