// flow-typed signature: f23dfb942c7351bcd821c54eef7e3951
// flow-typed version: <<STUB>>/shortid_v^2.2.4/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shortid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'shortid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shortid/Gruntfile' {
  declare module.exports: any;
}

declare module 'shortid/lib/alphabet' {
  declare module.exports: any;
}

declare module 'shortid/lib/decode' {
  declare module.exports: any;
}

declare module 'shortid/lib/encode' {
  declare module.exports: any;
}

declare module 'shortid/lib/index' {
  declare module.exports: any;
}

declare module 'shortid/lib/is-valid' {
  declare module.exports: any;
}

declare module 'shortid/lib/random/random-byte-browser' {
  declare module.exports: any;
}

declare module 'shortid/lib/random/random-byte' {
  declare module.exports: any;
}

declare module 'shortid/lib/random/random-from-seed' {
  declare module.exports: any;
}

declare module 'shortid/lib/util/cluster-worker-id-browser' {
  declare module.exports: any;
}

declare module 'shortid/lib/util/cluster-worker-id' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shortid/Gruntfile.js' {
  declare module.exports: $Exports<'shortid/Gruntfile'>;
}
declare module 'shortid/index' {
  declare module.exports: $Exports<'shortid'>;
}
declare module 'shortid/index.js' {
  declare module.exports: $Exports<'shortid'>;
}
declare module 'shortid/lib/alphabet.js' {
  declare module.exports: $Exports<'shortid/lib/alphabet'>;
}
declare module 'shortid/lib/decode.js' {
  declare module.exports: $Exports<'shortid/lib/decode'>;
}
declare module 'shortid/lib/encode.js' {
  declare module.exports: $Exports<'shortid/lib/encode'>;
}
declare module 'shortid/lib/index.js' {
  declare module.exports: $Exports<'shortid/lib/index'>;
}
declare module 'shortid/lib/is-valid.js' {
  declare module.exports: $Exports<'shortid/lib/is-valid'>;
}
declare module 'shortid/lib/random/random-byte-browser.js' {
  declare module.exports: $Exports<'shortid/lib/random/random-byte-browser'>;
}
declare module 'shortid/lib/random/random-byte.js' {
  declare module.exports: $Exports<'shortid/lib/random/random-byte'>;
}
declare module 'shortid/lib/random/random-from-seed.js' {
  declare module.exports: $Exports<'shortid/lib/random/random-from-seed'>;
}
declare module 'shortid/lib/util/cluster-worker-id-browser.js' {
  declare module.exports: $Exports<'shortid/lib/util/cluster-worker-id-browser'>;
}
declare module 'shortid/lib/util/cluster-worker-id.js' {
  declare module.exports: $Exports<'shortid/lib/util/cluster-worker-id'>;
}
