const USERNAME_TAKEN = 'error/USERNAME_TAKEN';
const PASSWORDS_DO_NOT_MATCH = 'error/PASSWORDS_DO_NOT_MATCH';
const INVALID_EMAIL = 'error/INVALID_EMAIL';
const EMAIL_TAKEN = 'error/EMAIL_TAKEN';
const RESET_TOKEN_INVALID = 'error/RESET_TOKEN_INVALID';
const UNKNOWN_ERROR = 'error/UNKNOWN';

export default {
  USERNAME_TAKEN,
  PASSWORDS_DO_NOT_MATCH,
  INVALID_EMAIL,
  EMAIL_TAKEN,
  RESET_TOKEN_INVALID,
  UNKNOWN_ERROR,
};
