// @flow

export type ModalType = 'LOGIN_MODAL' |
    'REQUEST_PASSWORD_RESET_MODAL' |
    'REGISTER_MODAL' |
    'USER_SETTINGS_MODAL';

export const LOGIN_MODAL: ModalType = 'LOGIN_MODAL';
export const REQUEST_PASSWORD_RESET_MODAL: ModalType = 'REQUEST_PASSWORD_RESET_MODAL';
export const REGISTER_MODAL: ModalType = 'REGISTER_MODAL';
export const USER_SETTINGS_MODAL: ModalType = 'USER_SETTINGS_MODAL';
