export const LOGIN_MODAL = 'LOGIN_MODAL';
export const REQUEST_PASSWORD_RESET_MODAL = 'REQUEST_PASSWORD_RESET_MODAL';
export const REGISTER_MODAL = 'REGISTER_MODAL';
export const USER_SETTINGS_MODAL = 'USER_SETTINGS_MODAL';
